### ISSUE TITLE
Problems rendering diagram blog posts

### ISSUE THREAD

**Issue by rnwolf** [hellotham/hello-astro#11] opened 2023-02-19 11:37 UTC
Hi I noticed that some of the example diagram blog posts don't render images.

Mindmap Diagram
https://hellotham.github.io/hello-astro/blog/2022-08-26-markmap-diagrams
![image](https://user-images.githubusercontent.com/117415/219945358-db393bfe-baba-4914-adfd-e5c781a7a0c7.png)

Mermaid Diagram
https://hellotham.github.io/hello-astro/blog/2022-08-20-mermaid-diagrams
![image](https://user-images.githubusercontent.com/117415/219945379-57261924-38a5-4775-a3a7-f543ad76be2e.png)

I have check with both Edge and Firefox browsers.

**Comment by ChristineTham** [comment] 2023-02-25 06:27
Hi - thanks for raising this issue. Looks like the issue is caused by me not using the rendered frontmatter for blog and doc posts. This should now be fixed in Release v2.4.1. Can you please check and confirm?

**Comment by rnwolf** [comment] 2023-02-26 20:44
Looking good. Thanks

**Closed** 2023-02-26 20:44 UTC
